bad_foods = {
    "Double cheeseburgers": {"calories": 800, "workout": "Running (1.5 hours)"},
    "Fried chicken (1 piece)": {"calories": 400, "workout": "Cycling (0.8 hours)"},
    "French fries (medium)": {"calories": 365, "workout": "Swimming (0.5 hours)"},
    "Hot dogs": {"calories": 150, "workout": "Walking (0.3 hours)"},
    "Pizza (slice with heavy toppings)": {"calories": 300, "workout": "Football (0.6 hours)"},
    "Potato chips (1 oz)": {"calories": 150, "workout": "Weightlifting (0.5 hours)"},
    "Doritos (1 oz)": {"calories": 140, "workout": "Running (0.2 hours)"},
    "Pretzels (1 oz)": {"calories": 110, "workout": "Cycling (0.2 hours)"},
    "Cheese puffs (1 oz)": {"calories": 150, "workout": "Swimming (0.2 hours)"},
    "Flavored popcorn (1 oz)": {"calories": 100, "workout": "Walking (0.2 hours)"},
    "Donuts (1)": {"calories": 250, "workout": "Running (0.5 hours)"},
    "Pastries (1)": {"calories": 300, "workout": "Cycling (0.6 hours)"},
    "Candy (chocolate bar)": {"calories": 230, "workout": "Swimming (0.3 hours)"},
    "Ice cream (1 cup)": {"calories": 250, "workout": "Football (0.5 hours)"},
    "Sugary cereals (1 cup)": {"calories": 150, "workout": "Weightlifting (0.3 hours)"},
    "Soda (12 oz)": {"calories": 150, "workout": "Running (0.2 hours)"},
    "Energy drinks (12 oz)": {"calories": 160, "workout": "Cycling (0.3 hours)"},
    "Sweetened iced teas (12 oz)": {"calories": 120, "workout": "Swimming (0.2 hours)"},
    "Milkshakes (12 oz)": {"calories": 500, "workout": "Football (1 hour)"},
    "Commercial fruit juices (12 oz)": {"calories": 150, "workout": "Weightlifting (0.3 hours)"},
    "Processed meats (2 oz)": {"calories": 200, "workout": "Running (0.4 hours)"},
    "White bread (1 slice)": {"calories": 70, "workout": "Cycling (0.1 hours)"},
    "Instant noodles (1 cup)": {"calories": 200, "workout": "Swimming (0.3 hours)"},
    "Processed cheese products (1 slice)": {"calories": 60, "workout": "Football (0.1 hours)"},
    "Frozen meals (1 serving)": {"calories": 350, "workout": "Weightlifting (0.7 hours)"}
}

okay_foods = {
    "Peanut butter (2 tbsp)": {"calories": 190, "workout": "Running (0.4 hours)"},
    "Cheese (1 oz)": {"calories": 110, "workout": "Cycling (0.2 hours)"},
    "Granola bars (1 bar)": {"calories": 200, "workout": "Swimming (0.3 hours)"},
    "Regular yogurt (6 oz)": {"calories": 150, "workout": "Football (0.3 hours)"},
    "Whole wheat bread (1 slice)": {"calories": 80, "workout": "Weightlifting (0.2 hours)"},
    "Canned soup (1 cup)": {"calories": 150, "workout": "Running (0.2 hours)"},
    "Frozen vegetables (1 cup)": {"calories": 100, "workout": "Cycling (0.1 hours)"},
    "Bagels (1)": {"calories": 250, "workout": "Swimming (0.4 hours)"},
    "Rice cakes (1)": {"calories": 35, "workout": "Football (0.1 hours)"},
    "Lightly salted nuts (1 oz)": {"calories": 170, "workout": "Weightlifting (0.3 hours)"},
    "Low-fat snacks (1 serving)": {"calories": 100, "workout": "Running (0.2 hours)"},
    "Diet sodas (12 oz)": {"calories": 0, "workout": "No workout needed"},
    "Flavored water (without added sugars) (12 oz)": {"calories": 0, "workout": "No workout needed"},
    "Whole grain crackers (5 pieces)": {"calories": 70, "workout": "Cycling (0.1 hours)"},
    "Certain protein bars (1 bar)": {"calories": 200, "workout": "Swimming (0.3 hours)"}
}

healthy_foods = {
    "Apples (1 medium)": {"calories": 95, "workout": "Running (0.2 hours)"},
    "Bananas (1 medium)": {"calories": 105, "workout": "Cycling (0.2 hours)"},
    "Oranges (1 medium)": {"calories": 62, "workout": "Swimming (0.1 hours)"},
    "Berries (1 cup)": {"calories": 60, "workout": "Football (0.1 hours)"},
    "Grapes (1 cup)": {"calories": 60, "workout": "Weightlifting (0.1 hours)"},
    "Spinach (1 cup)": {"calories": 7, "workout": "Running (few minutes)"},
    "Broccoli (1 cup)": {"calories": 55, "workout": "Cycling (0.1 hours)"},
    "Carrots (1 cup)": {"calories": 50, "workout": "Swimming (0.1 hours)"},
    "Bell peppers (1 medium)": {"calories": 30, "workout": "Football (few minutes)"},
    "Kale (1 cup)": {"calories": 33, "workout": "Weightlifting (few minutes)"},
    "Chicken breast (3 oz)": {"calories": 140, "workout": "Running (0.3 hours)"},
    "Salmon (3 oz)": {"calories": 180, "workout": "Cycling (0.4 hours)"},
    "Tofu (1/2 cup)": {"calories": 94, "workout": "Swimming (0.2 hours)"},
    "Legumes (1 cup lentils)": {"calories": 230, "workout": "Football (0.5 hours)"},
    "Eggs (1 large)": {"calories": 70, "workout": "Weightlifting (0.1 hours)"},
    "Quinoa (1 cup cooked)": {"calories": 220, "workout": "Running (0.4 hours)"},
    "Brown rice (1 cup cooked)": {"calories": 215, "workout": "Cycling (0.4 hours)"},
    "Oats (1/2 cup dry)": {"calories": 150, "workout": "Swimming (0.3 hours)"},
    "Whole grain pasta (1 cup cooked)": {"calories": 170, "workout": "Football (0.4 hours)"},
    "Barley (1 cup cooked)": {"calories": 200, "workout": "Weightlifting (0.4 hours)"},
    "Avocados (1/2 medium)": {"calories": 120, "workout": "Running (0.2 hours)"},
    "Nuts (1 oz almonds)": {"calories": 160, "workout": "Cycling (0.3 hours)"},
    "Seeds (1 oz chia)": {"calories": 140, "workout": "Swimming (0.3 hours)"},
    "Olive oil (1 tbsp)": {"calories": 120, "workout": "Football (0.2 hours)"},
    "Fatty fish (3 oz salmon)": {"calories": 180, "workout": "Weightlifting (0.4 hours)"}
}
